"""
Simple Neural Network Library
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Layer', 'Network', 'Node', 'sigmoid', 'tokenizer']
class Layer:
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> list[float]:
        ...
    @property
    def last_input(self) -> list[float]:
        ...
    @last_input.setter
    def last_input(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def last_output(self) -> list[float]:
        ...
    @last_output.setter
    def last_output(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def nodes(self) -> list[Node]:
        ...
    @nodes.setter
    def nodes(self, arg0: collections.abc.Sequence[Node]) -> None:
        ...
class Network:
    def __init__(self) -> None:
        ...
    def addLayer(self, size: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def backprop(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def dump_nn(self, filename: str = 'model.json') -> None:
        ...
    def forward(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> list[float]:
        ...
    def import_nn(self, filename: str = 'model.json') -> None:
        ...
    def trainLoop(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Node:
    def __init__(self) -> None:
        ...
    def forward(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> float:
        ...
    @property
    def bias(self) -> float:
        ...
    @bias.setter
    def bias(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def weights(self) -> list[float]:
        ...
    @weights.setter
    def weights(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
def sigmoid(arg0: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def tokenizer(arg0: str) -> list[float]:
    ...
