
# New Hyprpaper Syntax (Preload is no longer needed)
wallpaper {
    monitor = eDP-1
    path = /home/rjaradat/Pictures/daniel-leone-g30P1zcOzXo-unsplash.jpg
    fit_mode = cover
}

# Optional: Disable splash text over the background
splash = false

